## Loading data into Pandas

In [129]:
import pandas as pd
import numpy as np

# df = pd.read_csv('pokemon_data.csv')

# df.head(5)
# df_xlsx = pd.read_excel('pokemon_data.xlsx')
# df_xlsx.head(3)

df = pd.read_csv('pokemon_data.txt', delimiter='\t')

df.head(5)

# df['HP']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [62]:
# Load from a dictionary
d_dic ={'Name':['Bulbasaur','Ivysaur'],
        'Type 1':['Grass',np.nan]} 


df_dic = pd.DataFrame(data = d_dic)
df_dic
# df_dic.info()

df_dic.dropna(axis=0,inplace=True)
df_dic

        Name Type 1
0  Bulbasaur  Grass

[1 rows x 2 columns]

In [63]:
np_data = np.zeros(3)
np_df = pd.DataFrame(data=np_data.reshape(1,3), columns=['c1','c2','c3'])
np_df

    c1   c2   c3
0  0.0  0.0  0.0

[1 rows x 3 columns]

## Reading Data in Pandas

In [64]:
#### Read Headers
# list(df.columns)

## Read each Column
df2=df[['Name', 'Type 1', 'HP']]
df2
## Read Each Row
# df2.iloc[20:24]
# df.iloc[0:4]

for index, row in df.iterrows():
    print(row['Name'])
    print(row['Attack'])
    print('***')

# df.loc[df['Type 1'] == "Grass"]

## Read a specific location (R,C)
# df.iloc[2,1]

Bulbasaur
49
***
Ivysaur
62
***
Venusaur
82
***
VenusaurMega Venusaur
100
***
Charmander
52
***
Charmeleon
64
***
Charizard
84
***
CharizardMega Charizard X
130
***
CharizardMega Charizard Y
104
***
Squirtle
48
***
Wartortle
63
***
Blastoise
83
***
BlastoiseMega Blastoise
103
***
Caterpie
30
***
Metapod
20
***
Butterfree
45
***
Weedle
35
***
Kakuna
25
***
Beedrill
90
***
BeedrillMega Beedrill
150
***
Pidgey
45
***
Pidgeotto
60
***
Pidgeot
80
***
PidgeotMega Pidgeot
80
***
Rattata
56
***
Raticate
81
***
Spearow
60
***
Fearow
90
***
Ekans
60
***
Arbok
85
***
Pikachu
55
***
Raichu
90
***
Sandshrew
75
***
Sandslash
100
***
Nidoran (Female)
47
***
Nidorina
62
***
Nidoqueen
92
***
Nidoran (Male)
57
***
Nidorino
72
***
Nidoking
102
***
Clefairy
45
***
Clefable
70
***
Vulpix
41
***
Ninetales
76
***
Jigglypuff
45
***
Wigglytuff
70
***
Zubat
45
***
Golbat
80
***
Oddish
50
***
Gloom
65
***
Vileplume
80
***
Paras
70
***
Parasect
95
***
Venonat
55
***
Venomoth
65
***
Diglett
55
***
Dugtrio
80
***
Meowth
45
***
Persian
70
***
Psyduck
52
***
Golduck
82
***
Mankey
80
***
Primeape
105
***
Growlithe
70
***
Arcanine
110
***
Poliwag
50
***
Poliwhirl
65
***
Poliwrath
95
***
Abra
20
***
Kadabra
35
***
Alakazam
50
***
AlakazamMega Alakazam
50
***
Machop
80
***
Machoke
100
***
Machamp
130
***
Bellsprout
75
***
Weepinbell
90
***
Victreebel
105
***
Tentacool
40
***
Tentacruel
70
***
Geodude
80
***
Graveler
95
***
Golem
120
***
Ponyta
85
***
Rapidash
100
***
Slowpoke
65
***
Slowbro
75
***
SlowbroMega Slowbro
75
***
Magnemite
35
***
Magneton
60
***
Farfetch'd
65
***
Doduo
85
***
Dodrio
110
***
Seel
45
***
Dewgong
70
***
Grimer
80
***
Muk
105
***
Shellder
65
***
Cloyster
95
***
Gastly
35
***
Haunter
50
***
Gengar
65
***
GengarMega Gengar
65
***
Onix
45
***
Drowzee
48
***
Hypno
73
***
Krabby
105
***
Kingler
130
***
Voltorb
30
***
Electrode
50
***
Exeggcute
40
***
Exeggutor
95
***
Cubone
50
***
Marowak
80
***
Hitmonlee
120
***
Hitmonchan
105
***
Lickitung
55
***
Koffing
65
***
Weezing
90
***
Rhyhorn
85
***
Rhydon
130
***
Chansey
5
***
Tangela
55
***
Kangaskhan
95
***
KangaskhanMega Kangaskhan
125
***
Horsea
40
***
Seadra
65
***
Goldeen
67
***
Seaking
92
***
Staryu
45
***
Starmie
75
***
Mr. Mime
45
***
Scyther
110
***
Jynx
50
***
Electabuzz
83
***
Magmar
95
***
Pinsir
125
***
PinsirMega Pinsir
155
***
Tauros
100
***
Magikarp
10
***
Gyarados
125
***
GyaradosMega Gyarados
155
***
Lapras
85
***
Ditto
48
***
Eevee
55
***
Vaporeon
65
***
Jolteon
65
***
Flareon
130
***
Porygon
60
***
Omanyte
40
***
Omastar
60
***
Kabuto
80
***
Kabutops
115
***
Aerodactyl
105
***
AerodactylMega Aerodactyl
135
***
Snorlax
110
***
Articuno
85
***
Zapdos
90
***
Moltres
100
***
Dratini
64
***
Dragonair
84
***
Dragonite
134
***
Mewtwo
110
***
MewtwoMega Mewtwo X
190
***
MewtwoMega Mewtwo Y
150
***
Mew
100
***
Chikorita
49
***
Bayleef
62
***
Meganium
82
***
Cyndaquil
52
***
Quilava
64
***
Typhlosion
84
***
Totodile
65
***
Croconaw
80
***
Feraligatr
105
***
Sentret
46
***
Furret
76
***
Hoothoot
30
***
Noctowl
50
***
Ledyba
20
***
Ledian
35
***
Spinarak
60
***
Ariados
90
***
Crobat
90
***
Chinchou
38
***
Lanturn
58
***
Pichu
40
***
Cleffa
25
***
Igglybuff
30
***
Togepi
20
***
Togetic
40
***
Natu
50
***
Xatu
75
***
Mareep
40
***
Flaaffy
55
***
Ampharos
75
***
AmpharosMega Ampharos
95
***
Bellossom
80
***
Marill
20
***
Azumarill
50
***
Sudowoodo
100
***
Politoed
75
***
Hoppip
35
***
Skiploom
45
***
Jumpluff
55
***
Aipom
70
***
Sunkern
30
***
Sunflora
75
***
Yanma
65
***
Wooper
45
***
Quagsire
85
***
Espeon
65
***
Umbreon
65
***
Murkrow
85
***
Slowking
75
***
Misdreavus
60
***
Unown
72
***
Wobbuffet
33
***
Girafarig
80
***
Pineco
65
***
Forretress
90
***
Dunsparce
70
***
Gligar
75
***
Steelix
85
***
SteelixMega Steelix
125
***
Snubbull
80
***
Granbull
120
***
Qwilfish
95
***
Scizor
130
***
ScizorMega Scizor
150
***
Shuckle
10
***
Heracross
125
***
HeracrossMega Heracross
185
***
Sneasel
95
***
Teddiursa
80
***
Ursaring
130
***
Slugma
40
***
Magcargo
50
***
Swinub
50
***
Piloswine
100
***
Corsola
55
***
Remoraid
65
***
Octillery
105
***
Delibird
55
***
Mantine
40
***
Skarmory
80
***
Houndour
60
***
Houndoom
90
***
HoundoomMega Houndoom
90
***
Kingdra
95
***
Phanpy
60
***
Donphan
120
***
Porygon2
80
***
Stantler
95
***
Smeargle
20
***
Tyrogue
35
***
Hitmontop
95
***
Smoochum
30
***
Elekid
63
***
Magby
75
***
Miltank
80
***
Blissey
10
***
Raikou
85
***
Entei
115
***
Suicune
75
***
Larvitar
64
***
Pupitar
84
***
Tyranitar
134
***
TyranitarMega Tyranitar
164
***
Lugia
90
***
Ho-oh
130
***
Celebi
100
***
Treecko
45
***
Grovyle
65
***
Sceptile
85
***
SceptileMega Sceptile
110
***
Torchic
60
***
Combusken
85
***
Blaziken
120
***
BlazikenMega Blaziken
160
***
Mudkip
70
***
Marshtomp
85
***
Swampert
110
***
SwampertMega Swampert
150
***
Poochyena
55
***
Mightyena
90
***
Zigzagoon
30
***
Linoone
70
***
Wurmple
45
***
Silcoon
35
***
Beautifly
70
***
Cascoon
35
***
Dustox
50
***
Lotad
30
***
Lombre
50
***
Ludicolo
70
***
Seedot
40
***
Nuzleaf
70
***
Shiftry
100
***
Taillow
55
***
Swellow
85
***
Wingull
30
***
Pelipper
50
***
Ralts
25
***
Kirlia
35
***
Gardevoir
65
***
GardevoirMega Gardevoir
85
***
Surskit
30
***
Masquerain
60
***
Shroomish
40
***
Breloom
130
***
Slakoth
60
***
Vigoroth
80
***
Slaking
160
***
Nincada
45
***
Ninjask
90
***
Shedinja
90
***
Whismur
51
***
Loudred
71
***
Exploud
91
***
Makuhita
60
***
Hariyama
120
***
Azurill
20
***
Nosepass
45
***
Skitty
45
***
Delcatty
65
***
Sableye
75
***
SableyeMega Sableye
85
***
Mawile
85
***
MawileMega Mawile
105
***
Aron
70
***
Lairon
90
***
Aggron
110
***
AggronMega Aggron
140
***
Meditite
40
***
Medicham
60
***
MedichamMega Medicham
100
***
Electrike
45
***
Manectric
75
***
ManectricMega Manectric
75
***
Plusle
50
***
Minun
40
***
Volbeat
73
***
Illumise
47
***
Roselia
60
***
Gulpin
43
***
Swalot
73
***
Carvanha
90
***
Sharpedo
120
***
SharpedoMega Sharpedo
140
***
Wailmer
70
***
Wailord
90
***
Numel
60
***
Camerupt
100
***
CameruptMega Camerupt
120
***
Torkoal
85
***
Spoink
25
***
Grumpig
45
***
Spinda
60
***
Trapinch
100
***
Vibrava
70
***
Flygon
100
***
Cacnea
85
***
Cacturne
115
***
Swablu
40
***
Altaria
70
***
AltariaMega Altaria
110
***
Zangoose
115
***
Seviper
100
***
Lunatone
55
***
Solrock
95
***
Barboach
48
***
Whiscash
78
***
Corphish
80
***
Crawdaunt
120
***
Baltoy
40
***
Claydol
70
***
Lileep
41
***
Cradily
81
***
Anorith
95
***
Armaldo
125
***
Feebas
15
***
Milotic
60
***
Castform
70
***
Kecleon
90
***
Shuppet
75
***
Banette
115
***
BanetteMega Banette
165
***
Duskull
40
***
Dusclops
70
***
Tropius
68
***
Chimecho
50
***
Absol
130
***
AbsolMega Absol
150
***
Wynaut
23
***
Snorunt
50
***
Glalie
80
***
GlalieMega Glalie
120
***
Spheal
40
***
Sealeo
60
***
Walrein
80
***
Clamperl
64
***
Huntail
104
***
Gorebyss
84
***
Relicanth
90
***
Luvdisc
30
***
Bagon
75
***
Shelgon
95
***
Salamence
135
***
SalamenceMega Salamence
145
***
Beldum
55
***
Metang
75
***
Metagross
135
***
MetagrossMega Metagross
145
***
Regirock
100
***
Regice
50
***
Registeel
75
***
Latias
80
***
LatiasMega Latias
100
***
Latios
90
***
LatiosMega Latios
130
***
Kyogre
100
***
KyogrePrimal Kyogre
150
***
Groudon
150
***
GroudonPrimal Groudon
180
***
Rayquaza
150
***
RayquazaMega Rayquaza
180
***
Jirachi
100
***
DeoxysNormal Forme
150
***
DeoxysAttack Forme
180
***
DeoxysDefense Forme
70
***
DeoxysSpeed Forme
95
***
Turtwig
68
***
Grotle
89
***
Torterra
109
***
Chimchar
58
***
Monferno
78
***
Infernape
104
***
Piplup
51
***
Prinplup
66
***
Empoleon
86
***
Starly
55
***
Staravia
75
***
Staraptor
120
***
Bidoof
45
***
Bibarel
85
***
Kricketot
25
***
Kricketune
85
***
Shinx
65
***
Luxio
85
***
Luxray
120
***
Budew
30
***
Roserade
70
***
Cranidos
125
***
Rampardos
165
***
Shieldon
42
***
Bastiodon
52
***
Burmy
29
***
WormadamPlant Cloak
59
***
WormadamSandy Cloak
79
***
WormadamTrash Cloak
69
***
Mothim
94
***
Combee
30
***
Vespiquen
80
***
Pachirisu
45
***
Buizel
65
***
Floatzel
105
***
Cherubi
35
***
Cherrim
60
***
Shellos
48
***
Gastrodon
83
***
Ambipom
100
***
Drifloon
50
***
Drifblim
80
***
Buneary
66
***
Lopunny
76
***
LopunnyMega Lopunny
136
***
Mismagius
60
***
Honchkrow
125
***
Glameow
55
***
Purugly
82
***
Chingling
30
***
Stunky
63
***
Skuntank
93
***
Bronzor
24
***
Bronzong
89
***
Bonsly
80
***
Mime Jr.
25
***
Happiny
5
***
Chatot
65
***
Spiritomb
92
***
Gible
70
***
Gabite
90
***
Garchomp
130
***
GarchompMega Garchomp
170
***
Munchlax
85
***
Riolu
70
***
Lucario
110
***
LucarioMega Lucario
145
***
Hippopotas
72
***
Hippowdon
112
***
Skorupi
50
***
Drapion
90
***
Croagunk
61
***
Toxicroak
106
***
Carnivine
100
***
Finneon
49
***
Lumineon
69
***
Mantyke
20
***
Snover
62
***
Abomasnow
92
***
AbomasnowMega Abomasnow
132
***
Weavile
120
***
Magnezone
70
***
Lickilicky
85
***
Rhyperior
140
***
Tangrowth
100
***
Electivire
123
***
Magmortar
95
***
Togekiss
50
***
Yanmega
76
***
Leafeon
110
***
Glaceon
60
***
Gliscor
95
***
Mamoswine
130
***
Porygon-Z
80
***
Gallade
125
***
GalladeMega Gallade
165
***
Probopass
55
***
Dusknoir
100
***
Froslass
80
***
Rotom
50
***
RotomHeat Rotom
65
***
RotomWash Rotom
65
***
RotomFrost Rotom
65
***
RotomFan Rotom
65
***
RotomMow Rotom
65
***
Uxie
75
***
Mesprit
105
***
Azelf
125
***
Dialga
120
***
Palkia
120
***
Heatran
90
***
Regigigas
160
***
GiratinaAltered Forme
100
***
GiratinaOrigin Forme
120
***
Cresselia
70
***
Phione
80
***
Manaphy
100
***
Darkrai
90
***
ShayminLand Forme
100
***
ShayminSky Forme
103
***
Arceus
120
***
Victini
100
***
Snivy
45
***
Servine
60
***
Serperior
75
***
Tepig
63
***
Pignite
93
***
Emboar
123
***
Oshawott
55
***
Dewott
75
***
Samurott
100
***
Patrat
55
***
Watchog
85
***
Lillipup
60
***
Herdier
80
***
Stoutland
110
***
Purrloin
50
***
Liepard
88
***
Pansage
53
***
Simisage
98
***
Pansear
53
***
Simisear
98
***
Panpour
53
***
Simipour
98
***
Munna
25
***
Musharna
55
***
Pidove
55
***
Tranquill
77
***
Unfezant
115
***
Blitzle
60
***
Zebstrika
100
***
Roggenrola
75
***
Boldore
105
***
Gigalith
135
***
Woobat
45
***
Swoobat
57
***
Drilbur
85
***
Excadrill
135
***
Audino
60
***
AudinoMega Audino
60
***
Timburr
80
***
Gurdurr
105
***
Conkeldurr
140
***
Tympole
50
***
Palpitoad
65
***
Seismitoad
95
***
Throh
100
***
Sawk
125
***
Sewaddle
53
***
Swadloon
63
***
Leavanny
103
***
Venipede
45
***
Whirlipede
55
***
Scolipede
100
***
Cottonee
27
***
Whimsicott
67
***
Petilil
35
***
Lilligant
60
***
Basculin
92
***
Sandile
72
***
Krokorok
82
***
Krookodile
117
***
Darumaka
90
***
DarmanitanStandard Mode
140
***
DarmanitanZen Mode
30
***
Maractus
86
***
Dwebble
65
***
Crustle
95
***
Scraggy
75
***
Scrafty
90
***
Sigilyph
58
***
Yamask
30
***
Cofagrigus
50
***
Tirtouga
78
***
Carracosta
108
***
Archen
112
***
Archeops
140
***
Trubbish
50
***
Garbodor
95
***
Zorua
65
***
Zoroark
105
***
Minccino
50
***
Cinccino
95
***
Gothita
30
***
Gothorita
45
***
Gothitelle
55
***
Solosis
30
***
Duosion
40
***
Reuniclus
65
***
Ducklett
44
***
Swanna
87
***
Vanillite
50
***
Vanillish
65
***
Vanilluxe
95
***
Deerling
60
***
Sawsbuck
100
***
Emolga
75
***
Karrablast
75
***
Escavalier
135
***
Foongus
55
***
Amoonguss
85
***
Frillish
40
***
Jellicent
60
***
Alomomola
75
***
Joltik
47
***
Galvantula
77
***
Ferroseed
50
***
Ferrothorn
94
***
Klink
55
***
Klang
80
***
Klinklang
100
***
Tynamo
55
***
Eelektrik
85
***
Eelektross
115
***
Elgyem
55
***
Beheeyem
75
***
Litwick
30
***
Lampent
40
***
Chandelure
55
***
Axew
87
***
Fraxure
117
***
Haxorus
147
***
Cubchoo
70
***
Beartic
110
***
Cryogonal
50
***
Shelmet
40
***
Accelgor
70
***
Stunfisk
66
***
Mienfoo
85
***
Mienshao
125
***
Druddigon
120
***
Golett
74
***
Golurk
124
***
Pawniard
85
***
Bisharp
125
***
Bouffalant
110
***
Rufflet
83
***
Braviary
123
***
Vullaby
55
***
Mandibuzz
65
***
Heatmor
97
***
Durant
109
***
Deino
65
***
Zweilous
85
***
Hydreigon
105
***
Larvesta
85
***
Volcarona
60
***
Cobalion
90
***
Terrakion
129
***
Virizion
90
***
TornadusIncarnate Forme
115
***
TornadusTherian Forme
100
***
ThundurusIncarnate Forme
115
***
ThundurusTherian Forme
105
***
Reshiram
120
***
Zekrom
150
***
LandorusIncarnate Forme
125
***
LandorusTherian Forme
145
***
Kyurem
130
***
KyuremBlack Kyurem
170
***
KyuremWhite Kyurem
120
***
KeldeoOrdinary Forme
72
***
KeldeoResolute Forme
72
***
MeloettaAria Forme
77
***
MeloettaPirouette Forme
128
***
Genesect
120
***
Chespin
61
***
Quilladin
78
***
Chesnaught
107
***
Fennekin
45
***
Braixen
59
***
Delphox
69
***
Froakie
56
***
Frogadier
63
***
Greninja
95
***
Bunnelby
36
***
Diggersby
56
***
Fletchling
50
***
Fletchinder
73
***
Talonflame
81
***
Scatterbug
35
***
Spewpa
22
***
Vivillon
52
***
Litleo
50
***
Pyroar
68
***
Flabébé
38
***
Floette
45
***
Florges
65
***
Skiddo
65
***
Gogoat
100
***
Pancham
82
***
Pangoro
124
***
Furfrou
80
***
Espurr
48
***
MeowsticMale
48
***
MeowsticFemale
48
***
Honedge
80
***
Doublade
110
***
AegislashBlade Forme
150
***
AegislashShield Forme
50
***
Spritzee
52
***
Aromatisse
72
***
Swirlix
48
***
Slurpuff
80
***
Inkay
54
***
Malamar
92
***
Binacle
52
***
Barbaracle
105
***
Skrelp
60
***
Dragalge
75
***
Clauncher
53
***
Clawitzer
73
***
Helioptile
38
***
Heliolisk
55
***
Tyrunt
89
***
Tyrantrum
121
***
Amaura
59
***
Aurorus
77
***
Sylveon
65
***
Hawlucha
92
***
Dedenne
58
***
Carbink
50
***
Goomy
50
***
Sliggoo
75
***
Goodra
100
***
Klefki
80
***
Phantump
70
***
Trevenant
110
***
PumpkabooAverage Size
66
***
PumpkabooSmall Size
66
***
PumpkabooLarge Size
66
***
PumpkabooSuper Size
66
***
GourgeistAverage Size
90
***
GourgeistSmall Size
85
***
GourgeistLarge Size
95
***
GourgeistSuper Size
100
***
Bergmite
69
***
Avalugg
117
***
Noibat
30
***
Noivern
70
***
Xerneas
131
***
Yveltal
131
***
Zygarde50% Forme
100
***
Diancie
100
***
DiancieMega Diancie
160
***
HoopaHoopa Confined
110
***
HoopaHoopa Unbound
160
***
Volcanion
110
***

## Sorting/Describing Data

In [65]:
df.describe()

            #      HP  Attack  Defense  Sp. Atk  Sp. Def   Speed  Generation
count  800.00  800.00  800.00   800.00   800.00   800.00  800.00      800.00
mean   362.81   69.26   79.00    73.84    72.82    71.90   68.28        3.32
std    208.34   25.53   32.46    31.18    32.72    27.83   29.06        1.66
min      1.00    1.00    5.00     5.00    10.00    20.00    5.00        1.00
25%    184.75   50.00   55.00    50.00    49.75    50.00   45.00        2.00
50%    364.50   65.00   75.00    70.00    65.00    70.00   65.00        3.00
75%    539.25   80.00  100.00    90.00    95.00    90.00   90.00        5.00
max    721.00  255.00  190.00   230.00   194.00   230.00  180.00        6.00

[8 rows x 8 columns]

In [66]:
# sorted_df = df.sort_values('Name', ascending=False)

sorted_df = df.sort_values(['Name','Type 1','HP'], ascending=[1,1,0])#,inplace=True)

# sorted_df = df.sort_values([1,2,3],axis=1)#,inplace=True)
sorted_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

## Making changes to the data

In [67]:
# %%timeit
# df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
# df.head()
# type(df['Name'])
# df = df.drop(columns=['Total'])
# df.head()
df['Total'] = df.iloc[:, 4:10].sum(axis=1)


# list(df.columns.values)
# # [1,2]+[3]
# cols = list(df.columns)
# df = df[cols[0:4] + [cols[-1]]+cols[4:12]]

# df.head(5)

In [68]:
s= pd.Series([100,101,102])
# s.to_numpy()
d= s.to_frame(name='Col1')
d['Col1']

0    100
1    101
2    102
Name: Col1, Length: 3, dtype: int64

In [69]:
45+49+49+65+65+45

318

## Saving our Data (Exporting into Desired Format)

In [70]:
df2

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [71]:
# df2.to_csv('modified.csv', index=False)

#df.to_excel('modified.xlsx', index=False)

df2.to_csv('modified.txt', index=False, sep='\t')

## Filtering Data

In [77]:
# df['Type 1'] == 'Grass'

# df[df['Type 1'] == 'Grass']

# mask = (df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)
# mask
# new_df = df[mask]

# # new_df = new_df.reset_index()
# new_df.reset_index(drop=True, inplace=True)

# list(new_df.index)

# new_df.to_csv('filtered.csv')

new_df = df[df['Name'].str.contains('Mega ')]
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700

In [73]:
import re

# new_df = df[df['Name'].str.contains('^Pi\w*' , regex=True)]
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

In [84]:
# new_df.count()
new_df[new_df['Type 2'].isnull()]
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 3 to 796
Data columns (total 13 columns):
#             48 non-null int64
Name          48 non-null object
Type 1        48 non-null object
Type 2        39 non-null object
HP            48 non-null int64
Attack        48 non-null int64
Defense       48 non-null int64
Sp. Atk       48 non-null int64
Sp. Def       48 non-null int64
Speed         48 non-null int64
Generation    48 non-null int64
Legendary     48 non-null bool
Total         48 non-null int64
dtypes: bool(1), int64(9), object(3)
memory usage: 4.9+ KB


## Conditional Changes

In [128]:
# new_df.loc[new_df['Total'] > 500, 'Type 1'] = 'Flamer'
# new_df

# new_df.loc[new_df['Total'] > 500, 'Legendary'] = True
# new_df

# new_df.loc[df['Total'] >= 500, ['Generation','Legendary']] = [100, True]
# new_df

new_df.loc[new_df['Type 2'].isnull(), 'Type 2'] = 'Basic'
df

df = pd.read_csv('pokemon_data.csv')
df

KeyError: 'Type 2'

## Set index

In [103]:
# newdf = df.set_index('Name', drop=True)
# newdf = df.set_index('Name' , drop=False )
# newdf[newdf.index.str.contains('Pichu')]
# newdf = newdf.reset_index()
# newdf

# newdf = df.set_index(['Name','Type 1'] , drop=True )
# newdf
# newdf[(newdf.index.get_level_values('Name').str.contains('Pichu'))]

newdf[(newdf.index.get_level_values('Name').str.contains('Pichu'))
      |(newdf.index.get_level_values('Type 1').str.contains('Grass'))]

,,#,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,,,,,,,,,,
Bulbasaur,Grass,1,Poison,45,49,49,65,65,45,1,False
Ivysaur,Grass,2,Poison,60,62,63,80,80,60,1,False
Venusaur,Grass,3,Poison,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,3,Poison,80,100,123,122,120,80,1,False
Oddish,Grass,43,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Chespin,Grass,650,NaN,56,61,65,48,45,38,6,False
Quilladin,Grass,651,NaN,61,78,95,56,58,57,6,False
Chesnaught,Grass,652,Fighting,88,107,122,74,75,64,6,False
Skiddo,Grass,672,NaN,66,65,48,62,57,52,6,False
Gogoat,Grass,673,NaN,123,100,62,97,81,68,6,False

## Aggregate Statistics (Groupby)

In [114]:
# df = pd.read_csv('pokemon_data.csv')
# df

# df.groupby(['Type 1']).count()
# df.groupby(['Type 1']).mean()
# df.groupby(['Type 1']).mean()[['HP','Attack','Defense']]
# df.groupby(['Type 1']).mean()[['HP','Attack','Defense']].sort_values('Defense',ascending=False)
# df.groupby(['Type 1']).agg({'HP':'mean','Attack':'max','Defense':'min'}).sort_values('Defense',ascending=False)
# new syntax
# df.groupby('Type 1').agg(
#     min_HP=pd.NamedAgg(column='HP', aggfunc='min'),
#     max_Attack=pd.NamedAgg(column='Attack', aggfunc='max'),
#     average_Defense=pd.NamedAgg(column='Defense', aggfunc='mean'),
# )

df['c'] = 1
# df.groupby(['Type 1']).count()['c']
# df.groupby(['Type 1', 'Type 2']).count()['c']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: c, Length: 136, dtype: int64

In [125]:
# newdf = df[['Name','Type 1','HP']]
# res = newdf.groupby(['Type 1']).agg(list)
# res = df.groupby(['Type 1']).agg(list)['Name'] # the output is a series
# res['Bug']
res = df.groupby(['Type 1']).agg(list)['Name'].to_dict()
res

# res.tail(5)

{'Bug': ['Caterpie',
  'Metapod',
  'Butterfree',
  'Weedle',
  'Kakuna',
  'Beedrill',
  'BeedrillMega Beedrill',
  'Paras',
  'Parasect',
  'Venonat',
  'Venomoth',
  'Scyther',
  'Pinsir',
  'PinsirMega Pinsir',
  'Ledyba',
  'Ledian',
  'Spinarak',
  'Ariados',
  'Yanma',
  'Pineco',
  'Forretress',
  'Scizor',
  'ScizorMega Scizor',
  'Shuckle',
  'Heracross',
  'HeracrossMega Heracross',
  'Wurmple',
  'Silcoon',
  'Beautifly',
  'Cascoon',
  'Dustox',
  'Surskit',
  'Masquerain',
  'Nincada',
  'Ninjask',
  'Shedinja',
  'Volbeat',
  'Illumise',
  'Kricketot',
  'Kricketune',
  'Burmy',
  'WormadamPlant Cloak',
  'WormadamSandy Cloak',
  'WormadamTrash Cloak',
  'Mothim',
  'Combee',
  'Vespiquen',
  'Yanmega',
  'Sewaddle',
  'Swadloon',
  'Leavanny',
  'Venipede',
  'Whirlipede',
  'Scolipede',
  'Dwebble',
  'Crustle',
  'Karrablast',
  'Escavalier',
  'Joltik',
  'Galvantula',
  'Shelmet',
  'Accelgor',
  'Durant',
  'Larvesta',
  'Volcarona',
  'Genesect',
  'Scatterbug',
  'Spewpa',
  'Vivillon'],
 'Dark': ['Umbreon',
  'Murkrow',
  'Sneasel',
  'Houndour',
  'Houndoom',
  'HoundoomMega Houndoom',
  'Poochyena',
  'Mightyena',
  'Sableye',
  'SableyeMega Sableye',
  'Absol',
  'AbsolMega Absol',
  'Honchkrow',
  'Weavile',
  'Darkrai',
  'Purrloin',
  'Liepard',
  'Scraggy',
  'Scrafty',
  'Zorua',
  'Zoroark',
  'Pawniard',
  'Bisharp',
  'Vullaby',
  'Mandibuzz',
  'Deino',
  'Zweilous',
  'Hydreigon',
  'Inkay',
  'Malamar',
  'Yveltal'],
 'Dragon': ['Dratini',
  'Dragonair',
  'Dragonite',
  'Altaria',
  'AltariaMega Altaria',
  'Bagon',
  'Shelgon',
  'Salamence',
  'SalamenceMega Salamence',
  'Latias',
  'LatiasMega Latias',
  'Latios',
  'LatiosMega Latios',
  'Rayquaza',
  'RayquazaMega Rayquaza',
  'Gible',
  'Gabite',
  'Garchomp',
  'GarchompMega Garchomp',
  'Axew',
  'Fraxure',
  'Haxorus',
  'Druddigon',
  'Reshiram',
  'Zekrom',
  'Kyurem',
  'KyuremBlack Kyurem',
  'KyuremWhite Kyurem',
  'Goomy',
  'Sliggoo',
  'Goodra',
  'Zygarde50% Forme'],
 'Electric': ['Pikachu',
  'Raichu',
  'Magnemite',
  'Magneton',
  'Voltorb',
  'Electrode',
  'Electabuzz',
  'Jolteon',
  'Zapdos',
  'Pichu',
  'Mareep',
  'Flaaffy',
  'Ampharos',
  'AmpharosMega Ampharos',
  'Elekid',
  'Raikou',
  'Electrike',
  'Manectric',
  'ManectricMega Manectric',
  'Plusle',
  'Minun',
  'Shinx',
  'Luxio',
  'Luxray',
  'Pachirisu',
  'Magnezone',
  'Electivire',
  'Rotom',
  'RotomHeat Rotom',
  'RotomWash Rotom',
  'RotomFrost Rotom',
  'RotomFan Rotom',
  'RotomMow Rotom',
  'Blitzle',
  'Zebstrika',
  'Emolga',
  'Tynamo',
  'Eelektrik',
  'Eelektross',
  'ThundurusIncarnate Forme',
  'ThundurusTherian Forme',
  'Helioptile',
  'Heliolisk',
  'Dedenne'],
 'Fairy': ['Clefairy',
  'Clefable',
  'Cleffa',
  'Togepi',
  'Togetic',
  'Snubbull',
  'Granbull',
  'Togekiss',
  'Flabébé',
  'Floette',
  'Florges',
  'Spritzee',
  'Aromatisse',
  'Swirlix',
  'Slurpuff',
  'Sylveon',
  'Xerneas'],
 'Fighting': ['Mankey',
  'Primeape',
  'Machop',
  'Machoke',
  'Machamp',
  'Hitmonlee',
  'Hitmonchan',
  'Tyrogue',
  'Hitmontop',
  'Makuhita',
  'Hariyama',
  'Meditite',
  'Medicham',
  'MedichamMega Medicham',
  'Riolu',
  'Lucario',
  'LucarioMega Lucario',
  'Timburr',
  'Gurdurr',
  'Conkeldurr',
  'Throh',
  'Sawk',
  'Mienfoo',
  'Mienshao',
  'Pancham',
  'Pangoro',
  'Hawlucha'],
 'Fire': ['Charmander',
  'Charmeleon',
  'Charizard',
  'CharizardMega Charizard X',
  'CharizardMega Charizard Y',
  'Vulpix',
  'Ninetales',
  'Growlithe',
  'Arcanine',
  'Ponyta',
  'Rapidash',
  'Magmar',
  'Flareon',
  'Moltres',
  'Cyndaquil',
  'Quilava',
  'Typhlosion',
  'Slugma',
  'Magcargo',
  'Magby',
  'Entei',
  'Ho-oh',
  'Torchic',
  'Combusken',
  'Blaziken',
  'BlazikenMega Blaziken',
  'Numel',
  'Camerupt',
  'CameruptMega Camerupt',
  'Torkoal',
  'Chimchar',
  'Monferno',
  'Infernape',
  'Magmortar',
  'Heatran',
  'Tepig',
  'Pignite',
  'Emboar',
  'Pansear',
  'Simisear',
  'Darumaka',
  'DarmanitanStandard Mode',
  'DarmanitanZen Mode',
  'Heatmor',
  'Fennekin',
  'Braixen',
  'Delphox',
  'Fletchinder',
  'Talonflame',
  'Litleo',
  'Pyroar',
  'Volcanion'],
 'Flying': ['TornadusIncarnate Forme',
  'TornadusTherian Forme',
  'Noibat',
  'Noivern'],
 'Ghost': ['Gastly',
  'Haunter',
  'Gengar',
  'GengarMega Gengar',
  'Misdreavus',
  'Shuppet',
  'Banette',
  'BanetteMega Banette',
  'Duskull',
  'Dusclops',
  'Drifloon',
  'Drifblim',
  'Mismagius',
  'Spiritomb',
  'Dusknoir',
  'GiratinaAltered Forme',
  'GiratinaOrigin Forme',
  'Yamask',
  'Cofagrigus',
  'Litwick',
  'Lampent',
  'Chandelure',
  'Phantump',
  'Trevenant',
  'PumpkabooAverage Size',
  'PumpkabooSmall Size',
  'PumpkabooLarge Size',
  'PumpkabooSuper Size',
  'GourgeistAverage Size',
  'GourgeistSmall Size',
  'GourgeistLarge Size',
  'GourgeistSuper Size'],
 'Grass': ['Bulbasaur',
  'Ivysaur',
  'Venusaur',
  'VenusaurMega Venusaur',
  'Oddish',
  'Gloom',
  'Vileplume',
  'Bellsprout',
  'Weepinbell',
  'Victreebel',
  'Exeggcute',
  'Exeggutor',
  'Tangela',
  'Chikorita',
  'Bayleef',
  'Meganium',
  'Bellossom',
  'Hoppip',
  'Skiploom',
  'Jumpluff',
  'Sunkern',
  'Sunflora',
  'Treecko',
  'Grovyle',
  'Sceptile',
  'SceptileMega Sceptile',
  'Seedot',
  'Nuzleaf',
  'Shiftry',
  'Shroomish',
  'Breloom',
  'Roselia',
  'Cacnea',
  'Cacturne',
  'Tropius',
  'Turtwig',
  'Grotle',
  'Torterra',
  'Budew',
  'Roserade',
  'Cherubi',
  'Cherrim',
  'Carnivine',
  'Snover',
  'Abomasnow',
  'AbomasnowMega Abomasnow',
  'Tangrowth',
  'Leafeon',
  'ShayminLand Forme',
  'ShayminSky Forme',
  'Snivy',
  'Servine',
  'Serperior',
  'Pansage',
  'Simisage',
  'Cottonee',
  'Whimsicott',
  'Petilil',
  'Lilligant',
  'Maractus',
  'Foongus',
  'Amoonguss',
  'Ferroseed',
  'Ferrothorn',
  'Virizion',
  'Chespin',
  'Quilladin',
  'Chesnaught',
  'Skiddo',
  'Gogoat'],
 'Ground': ['Sandshrew',
  'Sandslash',
  'Diglett',
  'Dugtrio',
  'Cubone',
  'Marowak',
  'Rhyhorn',
  'Rhydon',
  'Gligar',
  'Phanpy',
  'Donphan',
  'Trapinch',
  'Vibrava',
  'Flygon',
  'Baltoy',
  'Claydol',
  'Groudon',
  'GroudonPrimal Groudon',
  'Hippopotas',
  'Hippowdon',
  'Rhyperior',
  'Gliscor',
  'Drilbur',
  'Excadrill',
  'Sandile',
  'Krokorok',
  'Krookodile',
  'Stunfisk',
  'Golett',
  'Golurk',
  'LandorusIncarnate Forme',
  'LandorusTherian Forme'],
 'Ice': ['Jynx',
  'Articuno',
  'Swinub',
  'Piloswine',
  'Delibird',
  'Smoochum',
  'Snorunt',
  'Glalie',
  'GlalieMega Glalie',
  'Spheal',
  'Sealeo',
  'Walrein',
  'Regice',
  'Glaceon',
  'Mamoswine',
  'Froslass',
  'Vanillite',
  'Vanillish',
  'Vanilluxe',
  'Cubchoo',
  'Beartic',
  'Cryogonal',
  'Bergmite',
  'Avalugg'],
 'Normal': ['Pidgey',
  'Pidgeotto',
  'Pidgeot',
  'PidgeotMega Pidgeot',
  'Rattata',
  'Raticate',
  'Spearow',
  'Fearow',
  'Jigglypuff',
  'Wigglytuff',
  'Meowth',
  'Persian',
  "Farfetch'd",
  'Doduo',
  'Dodrio',
  'Lickitung',
  'Chansey',
  'Kangaskhan',
  'KangaskhanMega Kangaskhan',
  'Tauros',
  'Ditto',
  'Eevee',
  'Porygon',
  'Snorlax',
  'Sentret',
  'Furret',
  'Hoothoot',
  'Noctowl',
  'Igglybuff',
  'Aipom',
  'Girafarig',
  'Dunsparce',
  'Teddiursa',
  'Ursaring',
  'Porygon2',
  'Stantler',
  'Smeargle',
  'Miltank',
  'Blissey',
  'Zigzagoon',
  'Linoone',
  'Taillow',
  'Swellow',
  'Slakoth',
  'Vigoroth',
  'Slaking',
  'Whismur',
  'Loudred',
  'Exploud',
  'Azurill',
  'Skitty',
  'Delcatty',
  'Spinda',
  'Swablu',
  'Zangoose',
  'Castform',
  'Kecleon',
  'Starly',
  'Staravia',
  'Staraptor',
  'Bidoof',
  'Bibarel',
  'Ambipom',
  'Buneary',
  'Lopunny',
  'LopunnyMega Lopunny',
  'Glameow',
  'Purugly',
  'Happiny',
  'Chatot',
  'Munchlax',
  'Lickilicky',
  'Porygon-Z',
  'Regigigas',
  'Arceus',
  'Patrat',
  'Watchog',
  'Lillipup',
  'Herdier',
  'Stoutland',
  'Pidove',
  'Tranquill',
  'Unfezant',
  'Audino',
  'AudinoMega Audino',
  'Minccino',
  'Cinccino',
  'Deerling',
  'Sawsbuck',
  'Bouffalant',
  'Rufflet',
  'Braviary',
  'MeloettaAria Forme',
  'MeloettaPirouette Forme',
  'Bunnelby',
  'Diggersby',
  'Fletchling',
  'Furfrou'],
 'Poison': ['Ekans',
  'Arbok',
  'Nidoran (Female)',
  'Nidorina',
  'Nidoqueen',
  'Nidoran (Male)',
  'Nidorino',
  'Nidoking',
  'Zubat',
  'Golbat',
  'Grimer',
  'Muk',
  'Koffing',
  'Weezing',
  'Crobat',
  'Gulpin',
  'Swalot',
  'Seviper',
  'Stunky',
  'Skuntank',
  'Skorupi',
  'Drapion',
  'Croagunk',
  'Toxicroak',
  'Trubbish',
  'Garbodor',
  'Skrelp',
  'Dragalge'],
 'Psychic': ['Abra',
  'Kadabra',
  'Alakazam',
  'AlakazamMega Alakazam',
  'Drowzee',
  'Hypno',
  'Mr. Mime',
  'Mewtwo',
  'MewtwoMega Mewtwo X',
  'MewtwoMega Mewtwo Y',
  'Mew',
  'Natu',
  'Xatu',
  'Espeon',
  'Unown',
  'Wobbuffet',
  'Lugia',
  'Celebi',
  'Ralts',
  'Kirlia',
  'Gardevoir',
  'GardevoirMega Gardevoir',
  'Spoink',
  'Grumpig',
  'Chimecho',
  'Wynaut',
  'DeoxysNormal Forme',
  'DeoxysAttack Forme',
  'DeoxysDefense Forme',
  'DeoxysSpeed Forme',
  'Chingling',
  'Mime Jr.',
  'Gallade',
  'GalladeMega Gallade',
  'Uxie',
  'Mesprit',
  'Azelf',
  'Cresselia',
  'Victini',
  'Munna',
  'Musharna',
  'Woobat',
  'Swoobat',
  'Sigilyph',
  'Gothita',
  'Gothorita',
  'Gothitelle',
  'Solosis',
  'Duosion',
  'Reuniclus',
  'Elgyem',
  'Beheeyem',
  'Espurr',
  'MeowsticMale',
  'MeowsticFemale',
  'HoopaHoopa Confined',
  'HoopaHoopa Unbound'],
 'Rock': ['Geodude',
  'Graveler',
  'Golem',
  'Onix',
  'Omanyte',
  'Omastar',
  'Kabuto',
  'Kabutops',
  'Aerodactyl',
  'AerodactylMega Aerodactyl',
  'Sudowoodo',
  'Larvitar',
  'Pupitar',
  'Tyranitar',
  'TyranitarMega Tyranitar',
  'Nosepass',
  'Lunatone',
  'Solrock',
  'Lileep',
  'Cradily',
  'Anorith',
  'Armaldo',
  'Regirock',
  'Cranidos',
  'Rampardos',
  'Shieldon',
  'Bastiodon',
  'Bonsly',
  'Probopass',
  'Roggenrola',
  'Boldore',
  'Gigalith',
  'Archen',
  'Archeops',
  'Terrakion',
  'Binacle',
  'Barbaracle',
  'Tyrunt',
  'Tyrantrum',
  'Amaura',
  'Aurorus',
  'Carbink',
  'Diancie',
  'DiancieMega Diancie'],
 'Steel': ['Steelix',
  'SteelixMega Steelix',
  'Skarmory',
  'Mawile',
  'MawileMega Mawile',
  'Aron',
  'Lairon',
  'Aggron',
  'AggronMega Aggron',
  'Beldum',
  'Metang',
  'Metagross',
  'MetagrossMega Metagross',
  'Registeel',
  'Jirachi',
  'Bronzor',
  'Bronzong',
  'Dialga',
  'Klink',
  'Klang',
  'Klinklang',
  'Cobalion',
  'Honedge',
  'Doublade',
  'AegislashBlade Forme',
  'AegislashShield Forme',
  'Klefki'],
 'Water': ['Squirtle',
  'Wartortle',
  'Blastoise',
  'BlastoiseMega Blastoise',
  'Psyduck',
  'Golduck',
  'Poliwag',
  'Poliwhirl',
  'Poliwrath',
  'Tentacool',
  'Tentacruel',
  'Slowpoke',
  'Slowbro',
  'SlowbroMega Slowbro',
  'Seel',
  'Dewgong',
  'Shellder',
  'Cloyster',
  'Krabby',
  'Kingler',
  'Horsea',
  'Seadra',
  'Goldeen',
  'Seaking',
  'Staryu',
  'Starmie',
  'Magikarp',
  'Gyarados',
  'GyaradosMega Gyarados',
  'Lapras',
  'Vaporeon',
  'Totodile',
  'Croconaw',
  'Feraligatr',
  'Chinchou',
  'Lanturn',
  'Marill',
  'Azumarill',
  'Politoed',
  'Wooper',
  'Quagsire',
  'Slowking',
  'Qwilfish',
  'Corsola',
  'Remoraid',
  'Octillery',
  'Mantine',
  'Kingdra',
  'Suicune',
  'Mudkip',
  'Marshtomp',
  'Swampert',
  'SwampertMega Swampert',
  'Lotad',
  'Lombre',
  'Ludicolo',
  'Wingull',
  'Pelipper',
  'Carvanha',
  'Sharpedo',
  'SharpedoMega Sharpedo',
  'Wailmer',
  'Wailord',
  'Barboach',
  'Whiscash',
  'Corphish',
  'Crawdaunt',
  'Feebas',
  'Milotic',
  'Clamperl',
  'Huntail',
  'Gorebyss',
  'Relicanth',
  'Luvdisc',
  'Kyogre',
  'KyogrePrimal Kyogre',
  'Piplup',
  'Prinplup',
  'Empoleon',
  'Buizel',
  'Floatzel',
  'Shellos',
  'Gastrodon',
  'Finneon',
  'Lumineon',
  'Mantyke',
  'Palkia',
  'Phione',
  'Manaphy',
  'Oshawott',
  'Dewott',
  'Samurott',
  'Panpour',
  'Simipour',
  'Tympole',
  'Palpitoad',
  'Seismitoad',
  'Basculin',
  'Tirtouga',
  'Carracosta',
  'Ducklett',
  'Swanna',
  'Frillish',
  'Jellicent',
  'Alomomola',
  'KeldeoOrdinary Forme',
  'KeldeoResolute Forme',
  'Froakie',
  'Frogadier',
  'Greninja',
  'Clauncher',
  'Clawitzer']}

## Working with large amounts of data

In [155]:
# for df in pd.read_csv('modified.csv', chunksize=5): #it returns an iterator for the lines of the file
#     print("CHUNK")
#     print(df)



new_df = pd.DataFrame(columns=df.columns)
# new_df

for df in pd.read_csv('pokemon_data.csv', chunksize=50):
    results = df.groupby(['Type 1'] , as_index=False).count()
    new_df = pd.concat([new_df, results] , sort=False , axis=1) #to concat horizontally use axis = 1

new_df['Attack']
# print(new_df[['Type 1']].to_dict())

# new_df.groupby('Type 1').sum()
# df=pd.read_csv('pokemon_data.csv')
# df.groupby('Type 1').count()

,Attack,Attack,Attack,Attack,Attack,Attack,Attack,...,Attack,Attack,Attack,Attack,Attack,Attack,Attack
0,NaN,7.0,4.0,3.0,4.0,8.0,5.0,...,7.0,1,2.0,9.0,8.0,4.0,3.0
1,NaN,2.0,2.0,4.0,3.0,6.0,2.0,...,1.0,2,2.0,4.0,7.0,5.0,4.0
2,NaN,2.0,5.0,2.0,6.0,2.0,2.0,...,4.0,8,5.0,1.0,4.0,2.0,3.0
3,NaN,7.0,4.0,2.0,3.0,2.0,2.0,...,2.0,1,5.0,3.0,3.0,3.0,6.0
4,NaN,6.0,1.0,3.0,4.0,1.0,7.0,...,3.0,2,7.0,2.0,2.0,2.0,1.0
5,NaN,2.0,4.0,3.0,4.0,5.0,7.0,...,4.0,3,2.0,5.0,1.0,7.0,1.0
6,NaN,10.0,2.0,4.0,1.0,1.0,2.0,...,4.0,6,11.0,3.0,3.0,2.0,2.0
7,NaN,10.0,5.0,1.0,6.0,3.0,1.0,...,1.0,3,5.0,3.0,4.0,6.0,10.0
8,NaN,4.0,2.0,8.0,1.0,5.0,8.0,...,9.0,3,3.0,4.0,3.0,2.0,2.0
9,NaN,NaN,4.0,2.0,6.0,3.0,2.0,...,2.0,3,8.0,2.0,3.0,6.0,2.0
10,NaN,NaN,3.0,3.0,5.0,1.0,4.0,...,2.0,4,NaN,7.0,3.0,3.0,2.0
11,NaN,NaN,14.0,2.0,7.0,3.0,8.0,...,5.0,6,NaN,2.0,2.0,1.0,9.0
12,NaN,NaN,NaN,13.0,NaN,10.0,NaN,...,2.0,1,NaN,5.0,4.0,2.0,3.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,1,NaN,NaN,3.0,5.0,2.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6,NaN,NaN,NaN,NaN,NaN

In [152]:
#split df into to dfs
cols=df.columns.to_list()
# left_df = df[cols[0:2]]
# left_df
# right_df = df[cols[1:3]+cols[3:]]
# right_df

# #inner join merge
# merged_inner = pd.merge(left=left_df,right=right_df, left_on='Name', right_on='Name')
# merged_inner

# left/right join
# left_df = pd.concat([left_df,pd.DataFrame(columns=list(left_df.columns),data=np.array(['','Div_left']).reshape(1,2))])
# left_df.reset_index(drop=True,inplace=True)
# left_df

# right_df = pd.concat([right_df,pd.DataFrame(columns=list(right_df.columns),data=np.array(['Div_right','','','','','','','','','','']).reshape(1,11))])
# right_df.reset_index(drop=True,inplace=True)
# right_df

# merged_left = pd.merge(left=left_df,right=right_df, left_on='Name', right_on='Name', how='right')
# merged_left

# # outer join
merged_outer = pd.merge(left=left_df,right=right_df, left_on='Name', right_on='Name', how='outer')
merged_outer

# pd.isnull(merged_outer.iloc[800]['Type 1'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,681,AegislashBlade Forme,Steel,Ghost,60,150,50,150,50,60,6,False
1,681,AegislashShield Forme,Steel,Ghost,60,50,150,50,150,60,6,False
2,682,Spritzee,Fairy,NaN,78,52,60,63,65,23,6,False
3,683,Aromatisse,Fairy,NaN,101,72,72,99,89,29,6,False
4,684,Swirlix,Fairy,NaN,62,48,66,59,57,49,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...
47,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
48,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
49,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True
50,,Div_left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,Div_right,,,,,,,,,,

## Display setting

In [58]:
display_settings = {
    'max_rows': 20,
    'precision': 2,
    'show_dimensions': True,
    'max_columns': 15
}

for op, value in display_settings.items():
    pd.set_option("display.{}".format(op), value)

In [60]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600